### ISSUE TITLE
Closing the wrong tab

### ISSUE THREAD

**Issue by Sirfrummel** [Evmorov/tab-close-double-click#3]
After I updated to Atom v 1.17, I have tab-close configured for shift-click and it's closing the tab to the _right_ now, not the tab I am clicking on.

**Comment by 14nd90** [comment]
+1

**Comment by burneyhoel** [comment]
+1 Same on 1.17.2 using double click.

**Comment by jamorales-bsft** [comment]
+1  v1.17.2 using double click

**Comment by drahgon55** [comment]
I was able to fix this issue myself. I submitted a PR. 

[https://github.com/evmorov/tab-close/pull/4](https://github.com/evmorov/tab-close/pull/4
)

Anyone wanting to fix this right now themselves it is pretty easy. Go into 

Atom->Preference->Packages->tab-close(under community packages)->Settings->View Code

In the code directory open:
lib->tab-close.coffee

Then make the changes in my PR. Note you have to use spaces not tabs when indenting or coffeescript complains about newlines. Next, completely close out of atom.io(on mac right click atom.io in dock and hit quit to fully exit). Then bam should work for you.

**Comment by evmorov** [comment]
New version has been uploaded
